/**
 * Zande Reports — PDF Export
 *
 * Formats structured accounting data into a branded PDF document.
 * Uses jsPDF and jspdf-autotable.
 *
 * Rules:
 *  - Accepts only structured data from the accounting layer
 *  - No raw DB calls
 *  - No UI side effects (triggers browser download directly)
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { 
  IncomeStatement, 
  VATResult, 
  CashFlowResult, 
  DebtorsAgingResult,
  ExpenseReportResult,
  InvoiceSummaryResult,
  ExecutiveSummaryResult
} from '../accounting/types';

// ─── Branding ────────────────────────────────────────────────────────────────

const BRAND = {
  name: 'Zande',
  primaryColor: [14, 165, 233] as [number, number, number],   // sky-500
  darkBg: [15, 23, 42] as [number, number, number],           // slate-900
  textLight: [241, 245, 249] as [number, number, number],     // slate-100
  textMuted: [100, 116, 139] as [number, number, number],     // slate-500
  successColor: [16, 185, 129] as [number, number, number],   // emerald-500
  dangerColor: [244, 63, 94] as [number, number, number],     // rose-500
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function fmt(n: number): string {
  return `R ${n.toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function addHeader(doc: jsPDF, title: string, period: string, businessName?: string) {
  // Dark header bar
  doc.setFillColor(...BRAND.darkBg);
  doc.rect(0, 0, 297, 28, 'F'); // Safe for landscape too

  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...BRAND.primaryColor);
  doc.text(BRAND.name, 14, 12);

  // Report title
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.textLight);
  doc.text(title, 14, 20);

  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Period + business
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text(`Period: ${period}`, pageWidth - 14, 10, { align: 'right' });
  if (businessName) {
    doc.text(businessName, pageWidth - 14, 16, { align: 'right' });
  }
  doc.text(`Generated: ${new Date().toLocaleDateString('en-ZA')}`, pageWidth - 14, 22, { align: 'right' });
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.internal.pages.length - 1;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.textMuted);
    
    doc.text('Generated by Zande Accounting Engine', 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
  }
}

function addDivider(doc: jsPDF, y: number, width = 196): void {
  doc.setDrawColor(30, 41, 59); // slate-800
  doc.setLineWidth(0.3);
  doc.line(14, y, width, y);
}

function addRow(
  doc: jsPDF,
  y: number,
  label: string,
  value: string,
  bold = false,
  valueColor?: [number, number, number],
  width = 196
): void {
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.setFontSize(9);
  doc.setTextColor(200, 210, 220);
  doc.text(label, 14, y);

  doc.setFont('courier', bold ? 'bold' : 'normal');
  if (valueColor) doc.setTextColor(...valueColor);
  else doc.setTextColor(241, 245, 249);
  doc.text(value, width, y, { align: 'right' });

  // Reset
  doc.setTextColor(200, 210, 220);
}

// ─── Income Statement PDF ─────────────────────────────────────────────────────

export function exportIncomeStatementPDF(
  data: IncomeStatement,
  businessName?: string
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const period = `${data.period.dateFrom} → ${data.period.dateTo}`;

  addHeader(doc, 'Income Statement', period, businessName);

  let y = 40;

  // Revenue section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('REVENUE', 14, y);
  y += 7;

  addRow(doc, y, 'Revenue (excl. VAT)', fmt(data.revenue.total_excl_vat));
  y += 6;
  addRow(doc, y, 'Output VAT', fmt(data.revenue.total_vat));
  y += 6;
  addRow(doc, y, 'Revenue (incl. VAT)', fmt(data.revenue.total_incl_vat), true);
  y += 4;
  addDivider(doc, y);
  y += 8;

  // Expenses section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('OPERATING EXPENSES', 14, y);
  y += 7;

  // Category breakdown using autoTable for better handling
  const expenseRows = Object.entries(data.expenses.by_category).map(([cat, amount]) => [
    cat.replace(/_/g, ' '),
    fmt(amount)
  ]);

  if (expenseRows.length > 0) {
    autoTable(doc, {
      startY: y,
      body: expenseRows,
      theme: 'plain',
      styles: { fontSize: 9, cellPadding: 2, textColor: [200, 210, 220] },
      columnStyles: {
        0: { font: 'helvetica' },
        1: { font: 'courier', halign: 'right' }
      },
      margin: { left: 14, right: 14 }
    });
    y = (doc as any).lastAutoTable.finalY + 4;
  }

  addRow(doc, y, 'Total Expenses (excl. VAT)', fmt(data.expenses.total_excl_vat), true);
  y += 4;
  addDivider(doc, y);
  y += 8;

  // Profit section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('PROFIT', 14, y);
  y += 7;

  addRow(doc, y, 'Gross Profit', fmt(data.gross_profit));
  y += 6;
  const profitColor = data.net_profit >= 0 ? BRAND.successColor : BRAND.dangerColor;
  addRow(doc, y, 'Net Profit', fmt(data.net_profit), true, profitColor);
  y += 6;
  addRow(doc, y, 'Net Margin', `${data.margin_pct.toFixed(1)}%`, true,
    data.margin_pct >= 0 ? BRAND.successColor : BRAND.dangerColor
  );

  addFooter(doc);
  doc.save(`income-statement-${data.period.dateFrom}-${data.period.dateTo}.pdf`);
}

// ─── VAT Report PDF ───────────────────────────────────────────────────────────

export function exportVATReportPDF(data: VATResult, businessName?: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const period = `${data.period.dateFrom} → ${data.period.dateTo}`;

  addHeader(doc, 'VAT Report (VAT201)', period, businessName);

  let y = 42;

  addRow(doc, y, 'Output VAT (Sales)', fmt(data.output_vat));
  y += 7;
  addRow(doc, y, 'Input VAT (Expenses — Claimable)', fmt(data.input_vat));
  y += 5;
  addDivider(doc, y);
  y += 8;

  const isRefund = data.vat_payable < 0;
  addRow(
    doc, y,
    isRefund ? 'VAT Refund Due from SARS' : 'VAT Payable to SARS',
    fmt(Math.abs(data.vat_payable)),
    true,
    isRefund ? BRAND.successColor : BRAND.dangerColor
  );

  addFooter(doc);
  doc.save(`vat-report-${data.period.dateFrom}-${data.period.dateTo}.pdf`);
}

// ─── Aged Debtors PDF ────────────────────────────────────────────────────────

export function exportDebtorsAgingPDF(data: DebtorsAgingResult, businessName?: string): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  addHeader(doc, `Aged Debtors — as at ${data.as_of_date}`, data.as_of_date, businessName);

  const tableData = data.lines.map(line => [
    line.invoice_number,
    line.client_name,
    line.due_date,
    fmt(line.invoice_total),
    fmt(line.payments_applied),
    fmt(line.outstanding),
    line.bucket.toUpperCase()
  ]);

  autoTable(doc, {
    startY: 35,
    head: [['Invoice #', 'Client', 'Due Date', 'Total', 'Paid', 'Outstanding', 'Bucket']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [22, 33, 55], textColor: [100, 116, 139], fontSize: 7, font: 'courier' },
    styles: { fontSize: 8, textColor: [200, 210, 220] },
    columnStyles: {
      3: { halign: 'right', font: 'courier' },
      4: { halign: 'right', font: 'courier' },
      5: { halign: 'right', font: 'courier', fontStyle: 'bold' },
      6: { halign: 'right', fontStyle: 'bold' }
    },
    didParseCell: function(data) {
      if (data.section === 'body' && data.column.index === 6) {
        const bucket = data.cell.raw as string;
        if (bucket === 'CURRENT') data.cell.styles.textColor = BRAND.successColor;
        else if (bucket === '31-60') data.cell.styles.textColor = [245, 158, 11];
        else if (bucket === '61-90') data.cell.styles.textColor = [249, 115, 22];
        else data.cell.styles.textColor = BRAND.dangerColor;
      }
      if (data.section === 'body' && data.column.index === 5) {
        const val = parseFloat((data.cell.raw as string).replace(/[^0-9.-]+/g,""));
        if (val > 0) data.cell.styles.textColor = BRAND.dangerColor;
        else data.cell.styles.textColor = BRAND.successColor;
      }
    }
  });

  let y = (doc as any).lastAutoTable.finalY + 10;
  
  addDivider(doc, y, 283);
  y += 6;
  addRow(doc, y, 'TOTAL OUTSTANDING', fmt(data.totals.total_outstanding), true, BRAND.dangerColor, 283);

  addFooter(doc);
  doc.save(`debtors-aging-${data.as_of_date}.pdf`);
}

// ─── Cash Flow PDF ───────────────────────────────────────────────────────────

export function exportCashFlowPDF(data: CashFlowResult, businessName?: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const period = `${data.period.dateFrom} → ${data.period.dateTo}`;

  addHeader(doc, 'Cash Flow Statement', period, businessName);

  let y = 42;

  addRow(doc, y, 'Opening Balance', fmt(data.opening_balance));
  y += 8;
  addRow(doc, y, 'Cash In (Payments Received)', fmt(data.cash_in), false, BRAND.successColor);
  y += 6;
  addRow(doc, y, 'Cash Out (Expenses Paid)', fmt(data.cash_out), false, BRAND.dangerColor);
  y += 5;
  addDivider(doc, y);
  y += 8;
  addRow(doc, y, 'Net Movement', fmt(data.net_movement), true,
    data.net_movement >= 0 ? BRAND.successColor : BRAND.dangerColor
  );
  y += 7;
  addRow(doc, y, 'Closing Balance', fmt(data.closing_balance), true,
    data.closing_balance >= 0 ? BRAND.successColor : BRAND.dangerColor
  );

  y += 12;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.textMuted);
  doc.text(
    'Note: Cash Out sourced from recorded expenses. Bank API integration for live feed data is planned.',
    14, y
  );

  addFooter(doc);
  doc.save(`cashflow-${data.period.dateFrom}-${data.period.dateTo}.pdf`);
}

// ─── Expense Report PDF ──────────────────────────────────────────────────────

export function exportExpenseReportPDF(data: ExpenseReportResult, businessName?: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const period = `${data.period.dateFrom} → ${data.period.dateTo}`;

  addHeader(doc, 'Expense Report', period, businessName);

  let y = 35;

  const tableData = data.lines.map(line => [
    line.expense_date,
    line.merchant,
    line.category.replace(/_/g, ' '),
    line.description,
    fmt(line.net_amount),
    fmt(line.vat_amount),
    fmt(line.amount)
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Merchant', 'Category', 'Description', 'Net', 'VAT', 'Gross']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [22, 33, 55], textColor: [100, 116, 139], fontSize: 7, font: 'courier' },
    styles: { fontSize: 7, textColor: [200, 210, 220] },
    columnStyles: {
      4: { halign: 'right', font: 'courier' },
      5: { halign: 'right', font: 'courier' },
      6: { halign: 'right', font: 'courier', fontStyle: 'bold' }
    }
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('SUBTOTALS BY CATEGORY', 14, y);
  y += 5;

  const summaryData = Object.entries(data.by_category).map(([cat, totals]) => [
    cat.replace(/_/g, ' '),
    totals.count.toString(),
    fmt(totals.net),
    fmt(totals.vat),
    fmt(totals.gross)
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Count', 'Net', 'VAT', 'Gross']],
    body: summaryData,
    theme: 'plain',
    headStyles: { textColor: [100, 116, 139], fontSize: 7, font: 'courier' },
    styles: { fontSize: 8, textColor: [200, 210, 220] },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right', font: 'courier' },
      3: { halign: 'right', font: 'courier' },
      4: { halign: 'right', font: 'courier', fontStyle: 'bold' }
    }
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  addDivider(doc, y);
  y += 6;
  addRow(doc, y, 'TOTAL EXPENSES (GROSS)', fmt(data.totals.total_gross), true);

  addFooter(doc);
  doc.save(`expense-report-${data.period.dateFrom}-${data.period.dateTo}.pdf`);
}

// ─── Invoice Summary PDF ─────────────────────────────────────────────────────

export function exportInvoiceSummaryPDF(data: InvoiceSummaryResult, businessName?: string): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const period = `${data.period.dateFrom} → ${data.period.dateTo}`;

  addHeader(doc, 'Invoice Summary', period, businessName);

  const tableData = data.lines.map(line => [
    line.invoice_number,
    line.client_name,
    line.issue_date,
    line.status,
    fmt(line.total),
    fmt(line.total - line.amount_due),
    fmt(line.amount_due)
  ]);

  autoTable(doc, {
    startY: 35,
    head: [['Invoice #', 'Client', 'Issue Date', 'Status', 'Total', 'Paid', 'Outstanding']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [22, 33, 55], textColor: [100, 116, 139], fontSize: 7, font: 'courier' },
    styles: { fontSize: 8, textColor: [200, 210, 220] },
    columnStyles: {
      4: { halign: 'right', font: 'courier' },
      5: { halign: 'right', font: 'courier' },
      6: { halign: 'right', font: 'courier', fontStyle: 'bold' }
    },
    didParseCell: function(data) {
      if (data.section === 'body' && data.column.index === 3) {
        const status = data.cell.raw as string;
        if (status === 'PAID') data.cell.styles.textColor = BRAND.successColor;
        else if (status === 'OVERDUE') data.cell.styles.textColor = BRAND.dangerColor;
        else if (status === 'SENT') data.cell.styles.textColor = [14, 165, 233];
      }
    }
  });

  let y = (doc as any).lastAutoTable.finalY + 10;
  
  addDivider(doc, y, 283);
  y += 6;
  addRow(doc, y, 'TOTAL INVOICED', fmt(data.totals.total_invoiced), true, undefined, 283);
  y += 6;
  addRow(doc, y, 'TOTAL OUTSTANDING', fmt(data.totals.total_outstanding), true, BRAND.dangerColor, 283);

  addFooter(doc);
  doc.save(`invoice-summary-${data.period.dateFrom}-${data.period.dateTo}.pdf`);
}

// ─── Executive Summary PDF ───────────────────────────────────────────────────

export function exportExecutiveSummaryPDF(data: ExecutiveSummaryResult): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const period = `${data.period.dateFrom} → ${data.period.dateTo}`;

  addHeader(doc, 'Executive Dashboard Summary', period, data.business_name);

  let y = 40;

  // Key Metrics Blocks
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.textLight);
  doc.text('KEY METRICS', 14, y);
  y += 8;

  // Box 1: Revenue
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, 88, 20, 'F');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('TOTAL REVENUE (EXCL. VAT)', 18, y + 6);
  doc.setFont('courier', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...BRAND.successColor);
  doc.text(fmt(data.revenue.total_excl_vat), 18, y + 14);

  // Box 2: Expenses
  doc.rect(106, y, 88, 20, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('TOTAL EXPENSES (EXCL. VAT)', 110, y + 6);
  doc.setFont('courier', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...BRAND.dangerColor);
  doc.text(fmt(data.expenses.total_excl_vat), 110, y + 14);

  y += 24;

  // Box 3: Net Profit
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, 88, 20, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('NET PROFIT', 18, y + 6);
  doc.setFont('courier', 'bold');
  doc.setFontSize(12);
  const profitColor = data.net_profit >= 0 ? BRAND.successColor : BRAND.dangerColor;
  doc.setTextColor(...profitColor);
  doc.text(fmt(data.net_profit), 18, y + 14);

  // Box 4: Margin
  doc.rect(106, y, 88, 20, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.textMuted);
  doc.text('NET MARGIN', 110, y + 6);
  doc.setFont('courier', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...profitColor);
  doc.text(`${data.margin_pct.toFixed(1)}%`, 110, y + 14);

  y += 30;

  // Cash & Debtors Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.textLight);
  doc.text('CASH & DEBTORS', 14, y);
  y += 6;

  addRow(doc, y, 'Net Cash Movement', fmt(data.cash_flow.net_movement), false, data.cash_flow.net_movement >= 0 ? BRAND.successColor : BRAND.dangerColor);
  y += 6;
  addRow(doc, y, 'Closing Bank Balance', fmt(data.cash_flow.closing_balance), true);
  y += 6;
  addRow(doc, y, 'Total Debtors Outstanding', fmt(data.debtors_total), true, BRAND.dangerColor);
  
  y += 12;

  // VAT & Activity
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.textLight);
  doc.text('VAT & ACTIVITY', 14, y);
  y += 6;

  const isRefund = data.vat.vat_payable < 0;
  addRow(doc, y, isRefund ? 'VAT Refund Due' : 'VAT Payable', fmt(Math.abs(data.vat.vat_payable)), true, isRefund ? BRAND.successColor : BRAND.dangerColor);
  y += 6;
  addRow(doc, y, 'Invoices Issued', data.invoice_count.toString());

  y += 12;

  // Top Expenses
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...BRAND.textLight);
  doc.text('TOP 5 EXPENSES', 14, y);
  y += 6;

  data.top_expense_categories.forEach(([cat, amount]) => {
    addRow(doc, y, cat.replace(/_/g, ' '), fmt(amount));
    y += 6;
  });

  addFooter(doc);
  doc.save(`executive-summary-${data.period.dateFrom}-${data.period.dateTo}.pdf`);
}
